# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tile metadata adapter for the mask GEMM kernel registry.

Thin wrapper over ``warpconvnet.csrc.mask_gemm.tile_metadata`` — a
self-contained snapshot emitted by warpgemm.autotune at codegen time.
Used by ``dispatch.py`` to reason about which tile will accept a
runtime problem shape (C_in, C_out, K, groups, dtypes).

The snapshot is regenerated by setting ``WARPGEMM_REGEN=1`` during a
source build; otherwise the checked-in copy is used. Drift between the
snapshot and live warpgemm is asserted by tests/csrc/test_warpgemm_drift.py.
"""

from __future__ import annotations

import dataclasses
from typing import Iterable

from warpconvnet.csrc.mask_gemm.tile_metadata import (
    build_tile_metadata,
    get_schema_version,
)
from .tile_metadata_sm100 import SM100_OVERLAY_TILES

_MIN_SCHEMA_VERSION = 7


def _build_tiles(*, active_only: bool, ops: Iterable[str] | None = None):
    """``build_tile_metadata`` plus the wcn-owned sm_100 deep-pipe overlay.

    Forward ids 1000-1009 are hand-written kernels warpgemm does not generate and
    has reserved to warpconvnet (see ``tile_metadata_sm100``). Every read of the
    tile registry goes through here so the overlay cannot be half-applied — the
    previous arrangement patched them into the generated file, where a regen
    silently dropped them.

    Overlay rows are appended, never merged over an existing id: warpgemm reserves
    1000-1049 and guards it, so a collision means that contract broke and should
    surface loudly rather than be papered over.
    """
    tiles = build_tile_metadata(active_only=active_only, ops=ops)
    overlay = SM100_OVERLAY_TILES
    if active_only:
        overlay = [t for t in overlay if t.tier == "production"]
    if ops is not None:
        wanted = set(ops)
        overlay = [t for t in overlay if t.op in wanted]
    if not overlay:
        return tiles
    collisions = {t.tile_id for t in tiles} & {t.tile_id for t in overlay}
    if collisions:
        raise RuntimeError(
            f"sm_100 overlay tile ids {sorted(collisions)} are also present in the "
            "warpgemm-generated metadata. warpgemm reserves forward 1000-1049 to "
            "warpconvnet; a collision means that reservation was violated. Re-run "
            "WARPGEMM_REGEN=1 against a warpgemm that vacates the range."
        )
    return tiles + overlay


# Backends this build can actually launch. The sm100_umma backend is a
# compile-parseable scaffold in warpgemm with no launchable pipeline; it must
# never be selected regardless of device arch (Blackwell handoff §3).
_LAUNCHABLE_BACKENDS = frozenset({"mma_sync"})


def _device_arch_code() -> int | None:
    """Current device SM capability as major*10+minor (e.g. 89 for Ada).

    Returns ``None`` when CUDA isn't initialized — caller should skip
    arch-gate filtering in that case (CI test collection, etc.).
    """
    import torch

    if not torch.cuda.is_available():
        return None
    major, minor = torch.cuda.get_device_capability(0)
    return major * 10 + minor


# Cache arch at import — SM capability doesn't change at runtime.
_DEVICE_ARCH: int | None = None


def _get_device_arch() -> int | None:
    global _DEVICE_ARCH
    if _DEVICE_ARCH is None:
        _DEVICE_ARCH = _device_arch_code()
    return _DEVICE_ARCH


def _arch_is_binary_compatible(compiled: int, device: int) -> bool:
    """True if a cubin built for ``compiled`` executes on SM ``device``.

    CUDA's rule for non-accelerated cubins: forward compatible across minor
    revisions **within one major version**. An ``sm_100`` binary runs on
    ``sm_103``; an ``sm_90`` binary does not, and neither does ``sm_120``.
    Verified on a GB300 by launching one exact-target cubin at a time and
    reading ``cudaGetLastError()``:

        sm_100 -> ok   sm_100f -> ok   sm_103 -> ok   sm_103a -> ok
        sm_90  -> "no kernel image"    sm_120 -> "no kernel image"
        sm_100a -> "no kernel image"   (accelerated cubins are exact-match)

    Only ``mma_sync`` tiles ever reach this check (see ``_LAUNCHABLE_BACKENDS``),
    and those are compiled without an ``a`` suffix, so the non-accelerated rule
    is the applicable one.
    """
    return compiled // 10 == device // 10 and compiled % 10 <= device % 10


def _tile_arch_allowed(meta, device_arch: int) -> bool:
    """True if ``meta`` is authorized to launch on SM ``device_arch``.

    Two questions are kept apart here, because conflating them is what stranded
    every mask_gemm tile on GB300:

    1. *Can the binary execute?* — ``_arch_is_binary_compatible``, above.
    2. *Was the tile validated for this device?* — policy, below.

    A ``compile_archs`` of length 1 is an exact pin: the SM120 experimental
    family ``(120,)``, the SM100 scaffold ``(100,)``, and the SM80-only tiles
    ``(80,)`` were each certified for one architecture only. Those are never
    inherited by a family member, so ``sm_121`` still cannot launch an
    SM120-pinned experimental tile.

    A multi-entry ``compile_archs`` is the broad certified production set
    (``(80, 86, 87, 89, 90, 100, 120)``) — generic tensor-core kernels validated
    across seven architectures. Those extend to binary-compatible minor
    revisions, which is what admits GB300 (``sm_103`` via ``100``) and GB10
    (``sm_121`` via ``120``).
    """
    archs = meta.compile_archs
    if device_arch in archs:
        return True
    if len(archs) < 2:
        return False
    return any(_arch_is_binary_compatible(a, device_arch) for a in archs)


# ---------------------------------------------------------------------------
# wcn dispatch-truth constraint override.
#
# Some (op, tile_id) binding arms launch a kernel whose canonical warpgemm
# metadata (kernel_struct + alignment/scalar constraints) describes a DIFFERENT
# kernel — the disease documented in ``kMaskGemmDispatchTruth`` (see
# mask_gemm_bindings.cu) and ``tests/csrc/test_mask_gemm_dispatch_truth.py``.
# The canonical single ``kernel_struct`` field cannot express wcn's evolved
# replacement (fused) or MW-dependent dispatch, so its correctness/alignment
# fields can be permissive lies. Example: tile 41 canonically names the scalar-A
# ``1s_flat_sa`` kernel (``c_in_alignment=1``, ``scalar_a=True``,
# ``min_per_group_c_in=1`` — "handles any C_in"), but the arm actually launches
# the vectorized ``2s_pipelined``/``1s_flat`` kernel, which REQUIRES 16B-aligned
# C_in. A gate reading the canonical fields (``TileMetadata.accepts`` /
# ``handles_c_in``) would wrongly admit tile 41 for a misaligned/small C_in.
#
# The wcn truth table is the authority: for each deviating tile, adopt the
# alignment/scalar CONSTRAINT fields of the canonical SIBLING tile that names the
# kernel actually launched. Only the constraint fields are corrected here —
# kernel_struct/tier/backend/compile_archs are left untouched so the warpgemm
# snapshot-drift guards (test_warpgemm_drift.py) still compare like-for-like and
# arch/backend authorization is unaffected.
#
# Practical exposure is low (the fwd/dgrad selectors use hard-coded alignment
# ladders, and the binding already rejects misaligned C loudly for these tiles),
# but this makes the override explicit so nothing upstream of the binding trusts
# a permissive-but-false alignment claim. See addition #2 of the launcher
# name-keying change-set.
#
# Not corrected: fwd ids 70/71/72 are an id-space OVERLOAD (canonical = an
# experimental 128x128 8-warp tile, wcn reuses the id as a scalar fallback). They
# are experimental-tier canonically (never production candidates) and routed
# before the canonical switch, so no gate reads them; the truth table documents
# them.
_CONSTRAINT_OVERRIDE_SIBLING: dict[tuple[str, int], int] = {
    ("forward", 41): 8,  # actual 2s_pipelined (MW1) / 1s_flat (MW>1) — both aligned
    ("forward", 2): 14,  # actual 128x64x32_2s_fused (constraints already match; explicit)
    ("dgrad", 0): 7,  # actual 64x64x32_1s_flat
    ("dgrad", 1): 25,  # actual 64x128x32_1s_flat_direpi
    ("dgrad", 24): 25,  # actual 64x128x32_1s_flat_direpi
}
_OVERRIDE_FIELDS = (
    "c_in_alignment",
    "c_out_alignment",
    "min_per_group_c_in",
    "min_per_group_c_out",
    "scalar_a",
    "scalar_b",
    "scalar_epi",
)

_RAW_INDEX: dict[str, dict[int, object]] = {}


def _raw_index(op: str) -> dict[int, object]:
    """Uncorrected full-registry index for ``op`` (sibling source for overrides)."""
    idx = _RAW_INDEX.get(op)
    if idx is None:
        idx = {t.tile_id: t for t in _build_tiles(active_only=False, ops=(op,))}
        _RAW_INDEX[op] = idx
    return idx


def _corrected(op: str, meta):
    """Return ``meta`` with constraint fields corrected to the actually-launched
    kernel's, per ``_CONSTRAINT_OVERRIDE_SIBLING``. No-op for non-deviating tiles."""
    sibling_id = _CONSTRAINT_OVERRIDE_SIBLING.get((op, meta.tile_id))
    if sibling_id is None:
        return meta
    sibling = _raw_index(op).get(sibling_id)
    if sibling is None:
        # Sibling absent (unexpected): leave canonical rather than guess.
        return meta
    return dataclasses.replace(meta, **{f: getattr(sibling, f) for f in _OVERRIDE_FIELDS})


def _get_tiles(op: str, filter_arch: bool = True):
    """Return active tile records for ``op``.

    ``filter_arch=True`` (default) drops tiles the current device may not launch
    — prevents arch-pinned tiles (e.g. 10/22/24/48/49 with compile_archs=(80,))
    from appearing in dispatch candidates on Ada. See ``_tile_arch_allowed`` for
    why this is not plain membership.

    Constraint fields for dispatch-truth deviating tiles are corrected via
    ``_corrected`` so ``accepts``/``handles_c_in`` reflect the kernel actually
    launched, not the canonical name's (see ``_CONSTRAINT_OVERRIDE_SIBLING``).
    """
    if get_schema_version() < _MIN_SCHEMA_VERSION:
        raise RuntimeError(
            f"tile_metadata schema_version "
            f"{get_schema_version()} < required {_MIN_SCHEMA_VERSION}"
        )
    tiles = [
        _corrected(op, t)
        for t in _build_tiles(active_only=True, ops=(op,))
        if t.backend in _LAUNCHABLE_BACKENDS
    ]
    if not filter_arch:
        return tiles
    arch = _get_device_arch()
    if arch is None:
        return tiles
    return [t for t in tiles if _tile_arch_allowed(t, arch)]


# Per-op tile_id -> metadata index over the FULL registry (all tiers, all
# backends, all archs). Built lazily once; used to authorize (possibly cached
# or pinned) tile ids before they reach the C++ dispatch switch.
_METADATA_INDEX: dict[str, dict[int, object]] = {}


def _metadata_index(op: str) -> dict[int, object]:
    idx = _METADATA_INDEX.get(op)
    if idx is None:
        if get_schema_version() < _MIN_SCHEMA_VERSION:
            raise RuntimeError(
                f"tile_metadata schema_version "
                f"{get_schema_version()} < required {_MIN_SCHEMA_VERSION}"
            )
        # Constraint-correct deviating tiles (see _CONSTRAINT_OVERRIDE_SIBLING);
        # no-op for the vast majority. Sibling source is the uncorrected raw index.
        idx = {tid: _corrected(op, t) for tid, t in _raw_index(op).items()}
        _METADATA_INDEX[op] = idx
    return idx


def known_tile_ids(op: str) -> frozenset:
    """All tile ids present in warpgemm metadata for ``op`` (any tier/arch)."""
    return frozenset(_metadata_index(op))


def tile_launch_rejection(op: str, tile_id: int) -> str | None:
    """Reason a canonical tile id must not launch on this device, or None if OK.

    Per the Blackwell handoff §3, every candidate path is authorized here before
    entering the C++ dispatch switch — including pinned tile ids read from the
    autotune cache. Two conditions must hold: a launchable backend, and an arch
    authorization that passes ``_tile_arch_allowed``.

    The arch check is binary compatibility within a major version (never a bare
    ``>=`` over arch codes, which would wrongly admit an sm_90 tile on sm_100),
    and single-arch pins remain exact so an experimental tile is never inherited
    by a newer device code. See ``_tile_arch_allowed``.

    Ids absent from warpgemm metadata (warpconvnet-only carve-outs such as the
    scalar/f32-out fallbacks) are the CALLER's responsibility to allowlist —
    this function returns a rejection for unknown ids so foreign/stale cached
    ids cannot slip through as "not in metadata, assume fine".
    """
    meta = _metadata_index(op).get(tile_id)
    if meta is None:
        return f"tile {tile_id} not present in warpgemm {op} metadata"
    if meta.backend not in _LAUNCHABLE_BACKENDS:
        return f"tile {tile_id} backend={meta.backend!r} is not launchable in this build"
    arch = _get_device_arch()
    if arch is not None and not _tile_arch_allowed(meta, arch):
        return (
            f"tile {tile_id} compile_archs={meta.compile_archs} excludes " f"device arch sm_{arch}"
        )
    return None


# ---------------------------------------------------------------------------
# Filter + rank (same shape as warpgemm's tile_metadata_example.py)
# ---------------------------------------------------------------------------


def candidate_tiles(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    tier: str = "production",
    acc_dtype: str | None = None,
) -> list:
    """Return tiles that will accept the runtime shape (correctness gate).

    Uses warpgemm's v4 ``TileMetadata.accepts(...)`` when ``acc_dtype`` is
    set; otherwise composes the pre-v4 helpers so callers that don't care
    about accumulator can still filter.
    """
    mw_needed = (K + 31) // 32
    tiles = _get_tiles(op)
    acc = acc_dtype or "f32"
    return [
        m
        for m in tiles
        if m.tier == tier and m.accepts(C_in, C_out, K, groups, input_dtype, output_dtype, acc)
    ]


def rank_candidates(
    candidates: Iterable,
    C_in: int,
    C_out: int,
    groups: int = 1,
    prefer_fp16_accum: bool = False,
) -> list:
    """Rank candidates by perf preference. Best first."""
    pref_acc = "f16" if prefer_fp16_accum else "f32"

    def key(m):
        return (
            not m.prefers_vectorized_c_in(C_in, groups),
            not m.prefers_vectorized_c_out(C_out, groups),
            m.acc_dtype != pref_acc,
            -(m.tile_m * m.tile_n),
            m.tile_id,
        )

    return sorted(candidates, key=key)


def pick_tile(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    prefer_fp16_accum: bool = False,
    acc_dtype: str | None = None,
) -> object | None:
    """Filter + rank + top candidate. None if no tile fits.

    ``acc_dtype`` (``"f16"`` or ``"f32"``) hard-filters on accumulator; when
    unset, ``prefer_fp16_accum`` biases the ranker instead.
    """
    c = candidate_tiles(op, C_in, C_out, K, groups, input_dtype, output_dtype, acc_dtype=acc_dtype)
    if not c:
        return None
    return rank_candidates(c, C_in, C_out, groups, prefer_fp16_accum)[0]


def explain(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    acc_dtype: str | None = None,
) -> str:
    """Human-readable diagnostic for a dispatch lookup."""
    mw_needed = (K + 31) // 32
    tiles = _get_tiles(op)
    out = [
        f"Problem: op={op} C_in={C_in} C_out={C_out} K={K} "
        f"groups={groups} dtypes={input_dtype}->{output_dtype}",
        f"Active {op} tiles: {len(tiles)}",
    ]

    survivors = []
    for t in tiles:
        if t.tier != "production":
            out.append(f"  reject tile {t.tile_id:>3}: tier={t.tier}")
            continue
        if not t.supports_mask_words(mw_needed):
            out.append(f"  reject tile {t.tile_id:>3}: mask_words={t.mask_words} < {mw_needed}")
            continue
        if not t.handles_c_in(C_in, groups):
            out.append(
                f"  reject tile {t.tile_id:>3}: C_in={C_in}/g={groups} fails "
                f"padded >= {t.min_per_group_c_in}"
            )
            continue
        if not t.handles_c_out(C_out, groups):
            out.append(
                f"  reject tile {t.tile_id:>3}: C_out={C_out}/g={groups} fails "
                f"padded >= {t.min_per_group_c_out}"
            )
            continue
        if not t.handles_dtypes(input_dtype, output_dtype):
            out.append(
                f"  reject tile {t.tile_id:>3}: dtypes {input_dtype}->{output_dtype} "
                f"not in {t.supported_input_dtypes}->{t.supported_output_dtypes}"
            )
            continue
        if acc_dtype is not None and not t.handles_accumulator(acc_dtype):
            out.append(
                f"  reject tile {t.tile_id:>3}: acc={acc_dtype} "
                f"not in {t.supported_accumulator_dtypes}"
            )
            continue
        survivors.append(t)

    out.append(f"Survivors: {len(survivors)}")
    ranked = rank_candidates(survivors, C_in, C_out, groups)
    for i, t in enumerate(ranked[:5]):
        vec_in = t.prefers_vectorized_c_in(C_in, groups)
        vec_out = t.prefers_vectorized_c_out(C_out, groups)
        out.append(
            f"  [{i}] tile {t.tile_id:>3} {t.kernel_struct}  "
            f"mnk=({t.tile_m},{t.tile_n},{t.tile_k})  acc={t.acc_dtype}  "
            f"vec_in={vec_in} vec_out={vec_out}"
        )
    return "\n".join(out)
