# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""wcn-owned tile metadata for the hand-written sm_100 deep-pipe forward tiles.

HAND-WRITTEN (NOT warpgemm-generated). Safe to edit.

These ten records used to be patched directly into
``csrc/mask_gemm/tile_metadata.py``, which is warpgemm-generated and carries a
"Do not edit by hand" banner. That was wrong in a way no test on a
warpgemm-less machine could see: ``WARPGEMM_REGEN=1 pip install -e .`` reverts
that file, which silently deleted eight of these ten records and reverted the
other two to a dead ``sm100_umma`` scaffold.

They live here instead because warpgemm genuinely cannot own them. A warpgemm
registry entry is a codegen INPUT -- registry -> generated header +
instantiations + enum + dispatch table -- and ``validate_registry()``
cross-checks emitted instantiations against the registry. There is no
``deep_pipe_xoffset`` mainloop in warpgemm's emitters, and the kernel is a
hand-written 490-line header (``csrc/mask_gemm/include/wcn_sm100_deep_pipe.h``).
Registering it would require an "external, do not emit" concept that weakens
the one invariant warpgemm enforces, to describe a kernel it can never
regenerate.

Every other artifact for these tiles is already a wcn carve-out: hand-written
header, own translation unit, own launch shims, own bindings arm, a wcn-only
tile tag, and a deliberate bypass of the generated ``FwdTile`` enum. This module
is that same carve-out for the metadata, matching how the 300-307 strided,
500-504 and 900-911 tiles are already handled.

Forward ids 1000-1049 are RESERVED for warpconvnet in the warpgemm registry,
enforced by ``validate_registry()`` (warpgemm/codegen/registry.py), which raises
``RegistryCoverageError`` if a warpgemm forward tile is ever registered there.
warpgemm's own forward Blackwell-native tiles live in 1050-1099 -- the dead
``sm100_umma`` forward scaffold was renumbered 1000/1001 -> 1050/1051 to vacate
this range. The dgrad (1100/1101) and wgrad (1200) umma scaffold is deliberately
untouched and must stay non-launchable.

All ten are ``tier="experimental"``, so ``build_tile_metadata(active_only=True)``
excludes them from ordinary dispatch pools; they are reached through the
override pools in ``algo_params_sm100.py``.
"""

from __future__ import annotations

from typing import List

from warpconvnet.csrc.mask_gemm.tile_metadata import TileMetadata

# Verified against a standalone nvcc 12.9 -gencode arch=compute_100a,code=sm_100a
# build (with -DWARPCONVNET_SM100_ENABLED=1 -- without it the whole TU is
# guarded out and compiles to nothing, a silent pass that proves nothing)
# build of all 20 instantiations (10 tiles x {half_t, bfloat16_t}): zero register
# spills, largest smem request 98,832 B (tile 1003) against B200's 232,448 B
# opt-in budget.
#
# compile_archs=(100,) is an EXACT pin -- sm_103 does not inherit it. The pin is
# justified by occupancy, not per-block capacity: tiles 1006-1009 carry
# __launch_bounds__ minBlocks targets, and minBlocks x smem exceeds consumer
# Blackwell's 102,400 B per-SM budget for 1006 (149,040), 1007 (133,184) and
# 1009 (112,176), so those tiles cannot reach their designed occupancy there.
_SM100_DEEP_PIPE_TILES: List[TileMetadata] = [
    TileMetadata(
        tile_id=1000,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x64x32",
        comment="SM100 deep-pipe 64x64x32 6s cross-offset persistent (49 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=64,
        tile_k=32,
        num_stages=6,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=64,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1001,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32",
        comment="SM100 deep-pipe 64x128x32 6s cross-offset persistent (74 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=6,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1002,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32",
        comment="SM100 deep-pipe 64x128x32 4s cross-offset persistent (49 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=4,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1003,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32",
        comment="SM100 deep-pipe 64x128x32 8s cross-offset persistent (98 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=8,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1004,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x64x32",
        comment="SM100 deep-pipe 64x64x32 10s cross-offset persistent (82 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=64,
        tile_k=32,
        num_stages=10,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=64,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1005,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32_8W",
        comment="SM100 deep-pipe 64x128x32 6s, 2x4 warps / 256 threads (74 KiB smem)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=6,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=1,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1006,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32",
        comment="SM100 deep-pipe 64x128x32 4s, launch_bounds minBlocks=3 (160 regs)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=4,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=3,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1007,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x64x32",
        comment="SM100 deep-pipe 64x64x32 4s, launch_bounds minBlocks=4 (124 regs)",
        tier="experimental",
        tile_m=64,
        tile_n=64,
        tile_k=32,
        num_stages=4,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=64,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=4,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1008,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x64x32",
        comment="SM100 deep-pipe 64x64x32 4s, launch_bounds minBlocks=3 (150 regs)",
        tier="experimental",
        tile_m=64,
        tile_n=64,
        tile_k=32,
        num_stages=4,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=64,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=3,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
    TileMetadata(
        tile_id=1009,
        op="forward",
        kernel_struct="MaskGemm_forward_sm100_deep_pipe",
        tile_tag="Tile64x128x32",
        comment="SM100 deep-pipe 64x128x32 3s, launch_bounds minBlocks=3 (159 regs)",
        tier="experimental",
        tile_m=64,
        tile_n=128,
        tile_k=32,
        num_stages=3,
        mainloop="deep_pipe_xoffset",
        epilogue="direct",
        acc_dtype="f32",
        supported_accumulator_dtypes=("f32",),
        supported_input_dtypes=("f16", "bf16"),
        supported_output_dtypes=("f16", "bf16"),
        mask_words=1,
        c_in_alignment=8,
        c_out_alignment=8,
        min_per_group_c_in=64,
        min_per_group_c_out=128,
        supports_groups=True,
        supports_identity_shortcut=True,
        supports_split_k=False,
        persistent=False,
        scalar_a=False,
        scalar_b=False,
        scalar_epi=False,
        use_smem_epilogue=True,
        use_b_kblock=False,
        split_offsets=1,
        min_blocks=3,
        backend="mma_sync",
        compile_archs=(100,),
        dispatch_mask_words=(1,),
    ),
]

# Public alias -- the name the consumer in
# nn/functional/sparse_conv/detail/tile_metadata.py imports.
SM100_OVERLAY_TILES: List[TileMetadata] = _SM100_DEEP_PIPE_TILES
