// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by warpgemm.codegen.generate_fwd.compose_fwd_helpers_iter_fragment().
// DO NOT EDIT — changes will be overwritten on next codegen run.
//
// Struct-body fragment for MaskGemm_forward_* tiles that match
// _uses_iter_helpers(cfg). #include'd inside private: of those tiles.
// References outer-struct constants (tM, tN, tK, kVec, MaskWords,
// ElementInput, ElementOutput, GmemTiledCopyB, UseSmemEpilogue, ...).

#include "warpgemm_a_loader_iter.cuh"

/// Warp-raked B load with pre-computed stride increments.
template <class SmemTensor>
__device__ void _load_B_warp_raked(const ElementInput *ptr_Bk,
                                   SmemTensor smem_stage,
                                   int n_start,
                                   int k_start,
                                   int C_out,
                                   int C_in) const {
  int warp_id = threadIdx.x / 32;
  int lane_id = threadIdx.x % 32;
  constexpr int kWarpDilN = tN / (MaxThreadsPerBlock / 32);
  constexpr int kWarpDilK = tK / kVec;

  int n_base = warp_id * kWarpDilN + (lane_id / kWarpDilK);
  int k_base = (lane_id % kWarpDilK) * kVec;

  constexpr int n_stride = 32 / kWarpDilK;
  constexpr int num_iters = tN / (n_stride * (MaxThreadsPerBlock / 32));

  int n_global = n_start + n_base;
  int k_global = k_start + k_base;
  int inc_strided_bytes = n_stride * sizeof(ElementInput);

  const char *gptr = reinterpret_cast<const char *>(&ptr_Bk[k_global * C_out + n_global]);
  // Group-conv alignment: cp.async.v4 needs 16-byte source. Misaligned when
  // ptr_Bk or C_out * sizeof(half) isn't 16-byte aligned (e.g. groups>1
  // with per-group C_out not multiple of kVec).
  bool b_aligned =
      ((reinterpret_cast<uintptr_t>(ptr_Bk) | (uintptr_t)(C_out * (int)sizeof(ElementInput))) &
       15u) == 0;

  CUTLASS_PRAGMA_UNROLL
  for (int s = 0; s < num_iters; ++s) {
    int n_cur = n_global + s * n_stride;
    uint32_t sa = cute::cast_smem_ptr_to_uint(&smem_stage(n_cur - n_start, k_base));
    bool ok =
        (n_cur + kVec <= n_start + tN) && (n_cur + kVec <= C_out) && (k_global + kVec <= C_in);

    if (ok && b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(sa),
                   "l"(gptr + s * inc_strided_bytes),
                   "n"(16));
    } else if (b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(sa),
                   "l"(gptr),
                   "n"(16),
                   "r"(0));
    } else {
      // Scalar fallback for misaligned source.
      int4 frag = make_int4(0, 0, 0, 0);
      if ((n_cur < C_out) && (k_global < C_in)) {
        const ElementInput *row_ptr = &ptr_Bk[k_global * C_out];
        ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
        CUTLASS_PRAGMA_UNROLL
        for (int v = 0; v < kVec; ++v) {
          int n = n_cur + v;
          if (n < C_out) dst[v] = row_ptr[n];
        }
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(sa),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

static constexpr bool BIsTransposed = false;

// Dense B load: CuTe TiledCopy for full tiles, fallback for boundary
template <class SmemTensor, class GmemThrCopyB>
__device__ void _load_B_tile(const ElementInput *ptr_Bk,
                             SmemTensor smem_stage,
                             GmemThrCopyB &gmem_thr_copy_B,
                             int n_start,
                             int k_start,
                             int C_out,
                             int C_in,
                             bool n_full_tile) const {
  using namespace cute;
  bool k_full_tile = (k_start + tK <= C_in);
  // Group-conv alignment for cp.async.v4: need ptr_Bk and C_out * sizeof(half)
  // both 16-byte aligned, otherwise &ptr_Bk[k*C_out + n] is misaligned.
  // Fall back to scalar B load when any group shift breaks alignment.
  bool b_aligned =
      ((reinterpret_cast<uintptr_t>(ptr_Bk) | (uintptr_t)(C_out * (int)sizeof(ElementInput))) &
       15u) == 0;
  if (n_full_tile && k_full_tile && sizeof(ElementInput) <= 2 && b_aligned) {
    // Full tile: use CuTe TiledCopy (fp16/bf16 only — fp32 uses cpasync fallback)
    Tensor gB_tile = make_tensor(make_gmem_ptr(ptr_Bk + n_start + k_start * C_out),
                                 make_shape(Int<tN>{}, Int<tK>{}),
                                 make_stride(Int<1>{}, C_out));
    auto thr_src_B = gmem_thr_copy_B.partition_S(gB_tile);
    auto thr_dst_B = gmem_thr_copy_B.partition_D(smem_stage);
    CUTLASS_PRAGMA_UNROLL
    for (int k = 0; k < size<2>(thr_src_B); ++k) {
      copy(GmemTiledCopyB{}, thr_src_B(_, _, k), thr_dst_B(_, _, k));
    }
  } else if (b_aligned) {
    // Partial tile but 16B-aligned source: use per-element cp.async with
    // src_bytes bounds. cp.async still requires 16B source alignment even
    // when src_bytes<16, so this branch is valid only when b_aligned.
    static_assert(tN % kVec == 0);
    constexpr int n_vecs = tN / kVec;
    constexpr int total_vecs = tK * n_vecs;
    CUTLASS_PRAGMA_UNROLL
    for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
      int k_local = idx / n_vecs;
      int nv = idx % n_vecs;
      int n_local = nv * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      // Use CuTe indexing for correct swizzled smem address
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_stage(n_local, k_local));
      if (k_global < C_in && n_global < C_out) {
        // Partial cp.async: load only valid bytes, zero-fill the rest.
        // Handles non-kVec-aligned C_out (e.g., C=7 loads 14 bytes, zeros 2).
        int valid_n = min(kVec, C_out - n_global);
        int src_bytes = valid_n * (int)sizeof(ElementInput);
        const void *src = &ptr_Bk[k_global * C_out + n_global];
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(src),
                     "n"(16),
                     "r"(src_bytes));
      } else {
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(ptr_Bk),
                     "n"(16),
                     "r"(0));
      }
    }
  } else {
    // Misaligned source (group-conv with per-group C % kVec != 0):
    // per-element ld.global + st.shared.v4. No alignment requirement.
    // Mirrors dense_b_transposed fallback and gathered_a_* scalar paths.
    static_assert(tN % kVec == 0);
    constexpr int n_vecs = tN / kVec;
    constexpr int total_vecs = tK * n_vecs;
    CUTLASS_PRAGMA_UNROLL
    for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
      int k_local = idx / n_vecs;
      int nv = idx % n_vecs;
      int n_local = nv * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_stage(n_local, k_local));
      int4 frag = make_int4(0, 0, 0, 0);
      if (k_global < C_in) {
        const ElementInput *row_ptr = &ptr_Bk[k_global * C_out];
        ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
        CUTLASS_PRAGMA_UNROLL
        for (int v = 0; v < kVec; ++v) {
          int n = n_global + v;
          if (n < C_out) dst[v] = row_ptr[n];
        }
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

/// Fallback: delegates to generic N-contiguous load.
template <class SmemTensor>
__device__ void _load_dense_B_cpasync(const ElementInput *ptr_B,
                                      SmemTensor smem_tile,
                                      int n_start,
                                      int k_start,
                                      int N,
                                      int K_dim) const {
  _load_dense_B_generic<SmemTensor, false>(ptr_B, smem_tile, n_start, k_start, N, K_dim);
}

/// Unified dense B load via cp.async, parameterized by layout.
template <class SmemTensor, bool IsTransposed>
__device__ void _load_dense_B_generic(const ElementInput *ptr_B,
                                      SmemTensor smem_tile,
                                      int n_start,
                                      int k_start,
                                      int N,
                                      int K_dim) const {
  static_assert(tN % kVec == 0);
  static_assert(tK % kVec == 0);
  constexpr int n_vecs = tN / kVec;
  constexpr int k_vecs = tK / kVec;
  // For N-contiguous: cp.async loads kVec elements along N. Iterate all K rows × N vectors.
  // For K-contiguous: cp.async loads kVec elements along K. Iterate all N rows × K vectors.
  constexpr int total_vecs = IsTransposed ? (tN * k_vecs) : (tK * n_vecs);
  // 128-bit cp.async needs a 16B-aligned source even when src_bytes<16. A
  // sub-16B weight base (DeepSpeed ZeRO contiguous-view weights) faults
  // "misaligned address". Guard on (base | stride*sizeof); scalar fallback
  // when misaligned. Stride: N (fwd, N-contig) / K_dim (transposed).
  int _b_stride_bytes = (IsTransposed ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;
  CUTLASS_PRAGMA_UNROLL
  for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
    int k_local, n_local;
    if constexpr (!IsTransposed) {
      // Forward (N-contiguous): K outer (step=1), N-vec inner (step=kVec)
      k_local = idx / n_vecs;
      n_local = (idx % n_vecs) * kVec;
    } else {
      // Transposed (K-contiguous): N outer (step=1), K-vec inner (step=kVec)
      n_local = idx / k_vecs;
      k_local = (idx % k_vecs) * kVec;
    }
    int n_global = n_start + n_local;
    int k_global = k_start + k_local;
    uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
    const void *src;
    int src_bytes;
    if constexpr (!IsTransposed) {
      // N-contiguous: vector along N, partial at N boundary
      int valid_n = (k_global < K_dim && n_global < N) ? min(kVec, N - n_global) : 0;
      src_bytes = valid_n * (int)sizeof(ElementInput);
      src = &ptr_B[k_global * N + n_global];
    } else {
      // K-contiguous: vector along K, partial at K boundary
      int valid_k = (n_global < N && k_global < K_dim) ? min(kVec, K_dim - k_global) : 0;
      src_bytes = valid_k * (int)sizeof(ElementInput);
      src = &ptr_B[n_global * K_dim + k_global];
    }
    if (src_bytes > 0 && b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(src),
                   "n"(16),
                   "r"(src_bytes));
    } else if (b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(ptr_B),
                   "n"(16),
                   "r"(0));
    } else {
      int4 frag = make_int4(0, 0, 0, 0);
      if (src_bytes > 0) {
        const ElementInput *s = reinterpret_cast<const ElementInput *>(src);
        ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
        int nvalid = src_bytes / (int)sizeof(ElementInput);
        CUTLASS_PRAGMA_UNROLL
        for (int e = 0; e < kVec; ++e)
          if (e < nvalid) d[e] = s[e];
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

/// Unified per-kblock B load for fused mainloop interleaving.
/// Warp-raked for both N-contiguous and K-contiguous cases.
template <class SmemTensor, int KB, bool IsTransposed = BIsTransposed>
__device__ void _load_B_kblock(const ElementInput *ptr_B,
                               SmemTensor smem_tile,
                               int n_start,
                               int k_start,
                               int N,
                               int K_dim) const {
  static_assert(tN % kVec == 0);
  constexpr int k_offset = KB * kMmaK;

  // 128-bit cp.async requires a 16B-aligned source even when src_bytes<16.
  // A sub-16B weight base (DeepSpeed ZeRO contiguous-view weights) faults
  // "misaligned address". Guard the cp.async path on (base | stride*sizeof);
  // fall back to per-element scalar load + st.shared.v4 when misaligned.
  // Stride between contiguous rows: N (fwd, N-contig) / K_dim (transposed).
  int _b_stride_bytes = (IsTransposed ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;

  if constexpr (!IsTransposed) {
    // Forward (N-contiguous): each cp.async loads kVec N-elements at 1 K-row.
    // Warp-raked: K outer (step=1), N-vec inner (step=kVec).
    constexpr int n_vecs = tN / kVec;
    constexpr int total_vecs = kMmaK * n_vecs;
    CUTLASS_PRAGMA_UNROLL
    for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
      int k_local = k_offset + idx / n_vecs;
      int n_local = (idx % n_vecs) * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
      int valid_n = (k_global < K_dim && n_global < N) ? min(kVec, N - n_global) : 0;
      int src_bytes = valid_n * (int)sizeof(ElementInput);
      if (src_bytes > 0 && b_aligned) {
        const void *src = &ptr_B[k_global * N + n_global];
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(src),
                     "n"(16),
                     "r"(src_bytes));
      } else if (b_aligned) {
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(ptr_B),
                     "n"(16),
                     "r"(0));
      } else {
        int4 frag = make_int4(0, 0, 0, 0);
        if (src_bytes > 0) {
          const ElementInput *s = &ptr_B[k_global * N + n_global];
          ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
          CUTLASS_PRAGMA_UNROLL
          for (int e = 0; e < kVec; ++e)
            if (n_global + e < N) d[e] = s[e];
        }
        asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                     "r"(frag.x),
                     "r"(frag.y),
                     "r"(frag.z),
                     "r"(frag.w));
      }
    }
  } else {
    // Transposed (K-contiguous): each cp.async loads kVec K-elements at 1 N-row.
    // Warp-raked: threads in a warp cover consecutive K-vectors at same N-row.
    constexpr int k_vecs_per_block = kMmaK / kVec;
    constexpr int k_threads = k_vecs_per_block;  // threads per N-row along K
    constexpr int n_per_wave = MaxThreadsPerBlock / k_threads;
    constexpr int num_waves = (tN + n_per_wave - 1) / n_per_wave;

    int k_tid = threadIdx.x % k_threads;
    int n_tid = threadIdx.x / k_threads;

    CUTLASS_PRAGMA_UNROLL
    for (int wave = 0; wave < num_waves; ++wave) {
      int n_local = wave * n_per_wave + n_tid;
      int k_local = k_offset + k_tid * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      if (n_local < tN) {
        uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
        int valid_k = (n_global < N && k_global < K_dim) ? min(kVec, K_dim - k_global) : 0;
        int src_bytes = valid_k * (int)sizeof(ElementInput);
        if (src_bytes > 0 && b_aligned) {
          const void *src = &ptr_B[n_global * K_dim + k_global];
          asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                       "l"(src),
                       "n"(16),
                       "r"(src_bytes));
        } else if (b_aligned) {
          asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                       "l"(ptr_B),
                       "n"(16),
                       "r"(0));
        } else {
          int4 frag = make_int4(0, 0, 0, 0);
          if (src_bytes > 0) {
            const ElementInput *s = &ptr_B[n_global * K_dim + k_global];
            ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
            CUTLASS_PRAGMA_UNROLL
            for (int e = 0; e < kVec; ++e)
              if (k_global + e < K_dim) d[e] = s[e];
          }
          asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                       "r"(frag.x),
                       "r"(frag.y),
                       "r"(frag.z),
                       "r"(frag.w));
        }
      }
    }
  }
}

// Legacy generic per-kblock B load (round-robin, non-raked — kept for reference).
template <class SmemTensor, int KB, bool IsTransposed_unused = BIsTransposed>
__device__ void _load_B_kblock_generic(const ElementInput *ptr_B,
                                       SmemTensor smem_tile,
                                       int n_start,
                                       int k_start,
                                       int N,
                                       int K_dim) const {
  static_assert(tN % kVec == 0);
  constexpr int n_vecs = tN / kVec;
  constexpr int k_offset = KB * kMmaK;
  constexpr int k_vecs = kMmaK / kVec;
  constexpr int total_vecs = IsTransposed_unused ? (tN * k_vecs) : (kMmaK * n_vecs);
  // Guard 128-bit cp.async on a 16B-aligned weight base (DeepSpeed ZeRO
  // contiguous-view weights are sub-16B → "misaligned address"). Stride:
  // N (fwd, N-contig) / K_dim (transposed). Scalar fallback when misaligned.
  int _b_stride_bytes = (IsTransposed_unused ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;

  CUTLASS_PRAGMA_UNROLL
  for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
    int k_local, n_local;
    if constexpr (!IsTransposed_unused) {
      k_local = k_offset + idx / n_vecs;
      n_local = (idx % n_vecs) * kVec;
    } else {
      n_local = idx / k_vecs;
      k_local = k_offset + (idx % k_vecs) * kVec;
    }
    int n_global = n_start + n_local;
    int k_global = k_start + k_local;
    uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
    bool pred;
    const void *src;
    if constexpr (!IsTransposed_unused) {
      pred = (k_global < K_dim) && (n_global + kVec <= N);
      src = &ptr_B[k_global * N + n_global];
    } else {
      pred = (n_global < N) && (k_global + kVec <= K_dim);
      src = &ptr_B[n_global * K_dim + k_global];
    }
    if (pred && b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(smem_addr),
                   "l"(src),
                   "n"(16));
    } else if (b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(ptr_B),
                   "n"(16),
                   "r"(0));
    } else {
      int4 frag = make_int4(0, 0, 0, 0);
      if (pred) {
        const ElementInput *s = reinterpret_cast<const ElementInput *>(src);
        ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
        CUTLASS_PRAGMA_UNROLL
        for (int e = 0; e < kVec; ++e) d[e] = s[e];
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

// Identity A loader: for submanifold center offset (real_rows[m] IS the input row).
// No pair_table lookup needed — simpler and faster than gathered A.
// Same smem layout as gathered A: smem_tile(m_row, k_col) with kVec-sized cp.async.
template <class SmemTensor>
__device__ void _load_A_identity(const ElementInput *ptr_A,
                                 const int *real_rows,
                                 SmemTensor smem_tile,
                                 int k_start,
                                 int N_in,
                                 int C_in,
                                 int stride_A) const {
  // Same iteration as gathered_a, but with in_row = real_rows[m].
  {
    // Group-conv alignment: cp.async.v4 needs 16-byte aligned source.
    // Misaligned when groups>1 AND per-group C_in not multiple of kVec.
    int _stride_bytes = stride_A * (int)sizeof(ElementInput);
    bool ptr_A_aligned =
        ((reinterpret_cast<uintptr_t>(ptr_A) | (uintptr_t)_stride_bytes) & 15u) == 0;
    constexpr int kItersPerThread = (tK / kVec * tM + MaxThreadsPerBlock - 1) / MaxThreadsPerBlock;
    CUTLASS_PRAGMA_UNROLL
    for (int iter = 0; iter < kItersPerThread; ++iter) {
      int idx = threadIdx.x + iter * MaxThreadsPerBlock;
      if (idx >= tK / kVec * tM) break;
      int pair_local = idx / (tK / kVec);
      int kv = idx % (tK / kVec);
      int k_local = kv * kVec;
      int k_global = k_start + k_local;
      int in_row = real_rows[pair_local];
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(pair_local, k_local));
      bool row_valid = (in_row >= 0) && (in_row < N_in);
      if (row_valid && (k_global + kVec <= C_in) && ptr_A_aligned) {
        const void *src = &ptr_A[in_row * stride_A + k_global];
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(smem_addr),
                     "l"(src),
                     "n"(16));
      } else {
        int4 frag = make_int4(0, 0, 0, 0);
        if (row_valid) {
          const ElementInput *row_ptr = ptr_A + in_row * stride_A;
          ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
          CUTLASS_PRAGMA_UNROLL
          for (int v = 0; v < kVec; ++v) {
            int k = k_global + v;
            if (k < C_in) dst[v] = row_ptr[k];
          }
        }
        asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                     "r"(frag.x),
                     "r"(frag.y),
                     "r"(frag.z),
                     "r"(frag.w));
      }
    }
  }
}

template <class Accumulator, class TiledMma_>
__device__ void _epilogue_direct(Accumulator &accum,
                                 ElementOutput *ptr_D,
                                 const int *mask_argsort,
                                 int m_start,
                                 int n_start,
                                 int N_out,
                                 int C_out,
                                 float alpha,
                                 TiledMma_ &tiled_mma,
                                 char *smem_buf,
                                 int stride_out = 0) const {
  if (stride_out == 0) stride_out = C_out;
  using namespace cute;
  auto thr_mma = tiled_mma.get_slice(threadIdx.x);
  Tensor tCrC = thr_mma.partition_C(make_identity_tensor(make_shape(Int<tM>{}, Int<tN>{})));

  if constexpr (sizeof(ElementOutput) == 2 && UseSmemEpilogue) {
    // Shared memory staging epilogue (CUTLASS pattern)
    constexpr int EPL_PAD = 8;
    constexpr int EPL_STRIDE = tN + EPL_PAD;
    // Stage in ElementOutput (half_t OR bfloat16_t), not __half — otherwise
    // bf16 output gets fp16 bits and the uint64 packed stores emit garbage.
    ElementOutput *epi_smem = reinterpret_cast<ElementOutput *>(smem_buf);

    CUTE_UNROLL
    for (int i = 0; i < size(accum); ++i) {
      auto coord = tCrC(i);
      float val = (alpha == 1.0f) ? float(accum(i)) : alpha * float(accum(i));
      epi_smem[get<0>(coord) * EPL_STRIDE + get<1>(coord)] = static_cast<ElementOutput>(val);
    }
    __syncthreads();

    constexpr int VEC = 4;
    constexpr int COLS_PER_THREAD = tN / VEC;
    constexpr int ROWS_PER_ITER = MaxThreadsPerBlock / COLS_PER_THREAD;
    int col_group = threadIdx.x % COLS_PER_THREAD;
    int row_in_iter = threadIdx.x / COLS_PER_THREAD;
    int col_start = col_group * VEC;

    // Group-conv alignment: uint64 stores need 8-byte alignment of the
    // target. ptr_D = ptr_D_base + group_id * C_per_group; if that shift
    // (plus stride_out*2) isn't 8-byte aligned, uint64 stores misalign.
    // Fall back to scalar writes in that case.
    bool epi_aligned = ((reinterpret_cast<uintptr_t>(ptr_D) |
                         (uintptr_t)(stride_out * (int)sizeof(ElementOutput))) &
                        7u) == 0;

#pragma unroll
    for (int iter = 0; iter < tM; iter += ROWS_PER_ITER) {
      int row = iter + row_in_iter;
      if (row < tM) {
        int sorted_row = m_start + row;
        if (sorted_row < N_out && col_start + n_start + VEC <= C_out && epi_aligned) {
          int out_row = mask_argsort[sorted_row];
          uint64_t packed;
          memcpy(&packed, &epi_smem[row * EPL_STRIDE + col_start], sizeof(uint64_t));
          char *dst = reinterpret_cast<char *>(ptr_D) +
                      ((size_t)out_row * stride_out + n_start + col_start) * 2;
          *reinterpret_cast<uint64_t *>(dst) = packed;
        } else if (sorted_row < N_out) {
          int out_row = mask_argsort[sorted_row];
          for (int v = 0; v < VEC; ++v) {
            int n_global = n_start + col_start + v;
            if (n_global < C_out) {
              ElementOutput h = epi_smem[row * EPL_STRIDE + col_start + v];
              memcpy(&ptr_D[out_row * stride_out + n_global], &h, 2);
            }
          }
        }
      }
    }
  } else if constexpr (sizeof(ElementOutput) == 2) {
    // Direct half2 epilogue (no smem staging — lower overhead for small tiles).
    // Half2 stores require 4-byte alignment: ptr_D (after per-group shift),
    // the column index (n_global), and the row stride (stride_out) must all
    // yield 4-byte-aligned target addresses.
    bool ptr_D_aligned = (reinterpret_cast<uintptr_t>(ptr_D) & 3u) == 0;
    bool stride_aligned = (stride_out & 1) == 0;
    CUTE_UNROLL
    for (int frag = 0; frag < size(accum); frag += 4) {
#pragma unroll
      for (int pair = 0; pair < 2; ++pair) {
        int base = frag + pair * 2;
        auto coord = tCrC(base);
        int sorted_row = m_start + get<0>(coord);
        int n_global = n_start + get<1>(coord);
        if (sorted_row < N_out && n_global + 1 < C_out && stride_aligned && ptr_D_aligned &&
            ((n_global & 1) == 0)) {
          int out_row = mask_argsort[sorted_row];
          float v0 = (alpha == 1.0f) ? float(accum(base)) : alpha * float(accum(base));
          float v1 = (alpha == 1.0f) ? float(accum(base + 1)) : alpha * float(accum(base + 1));
          // dtype-generic pack (half_t OR bfloat16_t); __float2half would
          // corrupt bf16 output. static_cast rounds float->ElementOutput.
          ElementOutput e0 = static_cast<ElementOutput>(v0), e1 = static_cast<ElementOutput>(v1);
          unsigned short s0, s1;
          memcpy(&s0, &e0, 2);
          memcpy(&s1, &e1, 2);
          uint32_t packed = (uint32_t)s0 | ((uint32_t)s1 << 16);
          char *base_ptr = reinterpret_cast<char *>(ptr_D);
          *reinterpret_cast<uint32_t *>(base_ptr + ((size_t)out_row * stride_out + n_global) * 2) =
              packed;
        } else if (sorted_row < N_out) {
          // Scalar fallback: either the write would straddle C (n_global+1 >= C)
          // or the half2 store would be misaligned (stride or col odd).
          int out_row = mask_argsort[sorted_row];
          if (n_global < C_out) {
            float val = (alpha == 1.0f) ? float(accum(base)) : alpha * float(accum(base));
            ptr_D[out_row * stride_out + n_global] = static_cast<ElementOutput>(val);
          }
          if (n_global + 1 < C_out) {
            float val1 = (alpha == 1.0f) ? float(accum(base + 1)) : alpha * float(accum(base + 1));
            ptr_D[out_row * stride_out + n_global + 1] = static_cast<ElementOutput>(val1);
          }
        }
      }
    }
  } else {
    // f32 output path: scalar stores
    CUTE_UNROLL
    for (int i = 0; i < size(accum); ++i) {
      auto coord = tCrC(i);
      int sorted_row = m_start + get<0>(coord);
      int n_global = n_start + get<1>(coord);
      if (sorted_row < N_out && n_global < C_out) {
        int out_row = mask_argsort[sorted_row];
        float val = float(accum(i));
        ElementOutput result = (alpha == 1.0f) ? static_cast<ElementOutput>(val)
                                               : static_cast<ElementOutput>(alpha * val);
        ptr_D[out_row * stride_out + n_global] = result;
      }
    }
  }
}

template <class Accumulator, class TiledMma_>
__device__ void _epilogue_scalar(Accumulator &accum,
                                 ElementOutput *ptr_D,
                                 const int *mask_argsort,
                                 int m_start,
                                 int n_start,
                                 int N_out,
                                 int C_out,
                                 float alpha,
                                 TiledMma_ &tiled_mma,
                                 int stride_out = 0) const {
  if (stride_out == 0) stride_out = C_out;
  using namespace cute;
  auto thr_mma = tiled_mma.get_slice(threadIdx.x);
  Tensor tCrC = thr_mma.partition_C(make_identity_tensor(make_shape(Int<tM>{}, Int<tN>{})));

  // Scalar epilogue: write one element at a time (no alignment requirement)
  CUTE_UNROLL
  for (int i = 0; i < size(accum); ++i) {
    auto coord = tCrC(i);
    int sorted_row = m_start + get<0>(coord);
    int n_global = n_start + get<1>(coord);
    if (sorted_row < N_out && n_global < C_out) {
      int out_row = mask_argsort[sorted_row];
      float val = (alpha == 1.0f) ? float(accum(i)) : alpha * float(accum(i));
      ptr_D[out_row * stride_out + n_global] = static_cast<ElementOutput>(val);
    }
  }
}
